accent: null
backgroundColor: '#ffffff'
subtle: null
paddingRegular: null
transitionDuration: null
paddingWide: null
fontSizeSmall: 70%
monospaceFont: null
primaryFont: null
rootHeight: null
rootWidth: 100%
rootZIndex: null
avatarBorderRadius: null
avatarSize: null
botAvatarBackgroundColor: null
botAvatarImage: null
botAvatarInitials: ''
userAvatarBackgroundColor: null
userAvatarImage: null
userAvatarInitials: null
showAvatarInGroup: null
bubbleBackground: '#eaeaea'
bubbleBorderColor: null
bubbleBorderRadius: 8
bubbleBorderStyle: null
bubbleBorderWidth: null
bubbleFromUserBackground: '#cbe8f7'
bubbleFromUserBorderColor: null
bubbleFromUserBorderRadius: 8
bubbleFromUserBorderStyle: null
bubbleFromUserBorderWidth: null
bubbleFromUserNubOffset: null
bubbleFromUserNubSize: 0
bubbleFromUserTextColor: '#212529'
bubbleImageHeight: null
bubbleMaxWidth: null
bubbleMinHeight: null
bubbleMinWidth: null
bubbleNubOffset: null
bubbleNubSize: null
bubbleTextColor: '#212529'
messageActivityWordBreak: null
connectivityIconPadding: null
connectivityMarginLeftRight: null
connectivityMarginTopBottom: null
connectivityTextSize: null
failedConnectivity: null
slowConnectivity: null
notificationText: null
slowConnectionAfter: null
emojiSet: null
internalLiveRegionFadeAfter: null
markdownRespectCRLF: null
markdownExternalLinkIconImage: null
hideScrollToEndButton: null
autoScrollSnapOnActivity: null
autoScrollSnapOnActivityOffset: null
autoScrollSnapOnPage: true
autoScrollSnapOnPageoffset: -300
hideSendBox: null
hideUploadButton: null
microphoneButtonColorOnDictate: null
sendBoxBackground: '#fff'
sendBoxButtonColor: null
sendBoxButtonColorOnDisabled: null
sendBoxButtonColorOnFocus: null
sendBoxButtonColorOnHover: null
sendBoxDisabledTextColor: null
sendBoxHeight: null
sendBoxMaxHeight: null
sendBoxTextColor: '#555555'
sendBoxBorderBottom: null
sendBoxBorderLeft: null
sendBoxBorderRight: null
sendBoxBorderTop: null
sendBoxPlaceholderColor: null
sendBoxTextWrap: null
sendBoxButtonAlignment: null
showSpokenText: null
spinnerAnimationBackgroundImage: null
spinnerAnimationHeight: null
spinnerAnimationWidth: null
spinnerAnimationPadding: null
suggestedActionBackground: null
suggestedActionBorderColor: null
suggestedActionBorderRadius: null
suggestedActionBorderStyle: null
suggestedActionBorderWidth: null
suggestedActionDisabledBackground: null
suggestedActionDisabledBorderColor: null
suggestedActionDisabledBorderStyle: null
suggestedActionDisabledBorderWidth: null
suggestedActionDisabledTextColor: null
suggestedActionHeight: null
suggestedActionImageHeight: null
suggestedActionLayout: null
suggestedActionTextColor: null
suggestedActionsCarouselFlipperCursor: null
suggestedActionsCarouselFlipperBoxWidth: null
suggestedActionsCarouselFlipperSize: null
suggestedActionsFlowMaxHeight: null
suggestedActionsStackedHeight: null
suggestedActionsStackedOverflow: null
suggestedActionsStackedLayoutButtonMaxHeight: null
suggestedActionsStackedLayoutButtonTextWrap: false
groupTimestamp: null
sendTimeout: null
sendTimeoutForAttachments: null
timestampColor: null
timestampFormat: absolute
transcriptTerminatorBackgroundColor: null
transcriptTerminatorBorderRadius: null
transcriptTerminatorColor: null
transcriptTerminatorFontSize: null
transcriptActivityVisualKeyboardIndicatorColor: null
transcriptActivityVisualKeyboardIndicatorStyle: null
transcriptActivityVisualKeyboardIndicatorWidth: null
transcriptVisualKeyboardIndicatorColor: null
transcriptVisualKeyboardIndicatorStyle: null
transcriptVisualKeyboardIndicatorWidth: null
scrollToEndButtonBehavior: null
scrollToEndButtonFontSize: null
newMessagesButtonFontSize: null
transcriptOverlayButtonBackground: null
transcriptOverlayButtonBackgroundOnDisabled: null
transcriptOverlayButtonBackgroundOnFocus: null
transcriptOverlayButtonBackgroundOnHover: null
transcriptOverlayButtonColor: null
transcriptOverlayButtonColorOnDisabled: null
transcriptOverlayButtonColorOnFocus: null
transcriptOverlayButtonColorOnHover: null
notificationDebounceTimeout: null
hideToaster: null
toasterHeight: null
toasterMaxHeight: null
toasterSingularMaxHeight: null
toastFontSize: null
toastIconWidth: null
toastSeparatorColor: null
toastTextPadding: null
toastErrorBackgroundColor: null
toastErrorColor: null
toastInfoBackgroundColor: null
toastInfoColor: null
toastSuccessBackgroundColor: null
toastSuccessColor: null
toastWarnBackgroundColor: null
toastWarnColor: null
typingAnimationBackgroundImage: null
typingAnimationDuration: null
typingAnimationHeight: null
typingAnimationWidth: null
enableUploadThumbnail: null
uploadThumbnailContentType: null
uploadThumbnailHeight: null
uploadThumbnailQuality: null
uploadThumbnailWidth: null
videoHeight: null
adaptiveCardsParserMaxVersion: null
cardEmphasisBackgroundColor: '#fafafa'
cardPushButtonBackgroundColor: null
cardPushButtonTextColor: null
richCardWrapTitle: null
